const KEYWORDS = [
  "activities assistant",
  "activity aide",
  "administrative medical assistant",
  "bsn",
  "care assistant",
  "care giver",
  "caregiver",
  "carer",
  "ccma",
  "certified clinical administrative assistant",
  "certified clinical medical administrative assistant",
  "certified home health aide",
  "certified homemaker-home health aide",
  "certified medical assistant",
  "certified medication aide",
  "certified medication tech",
  "certified medicine aide",
  "certified nurse aide",
  "certified nursing assistant",
  "certified residential medicine aide",
  "chha",
  "clinical tech",
  "clinical technician",
  "cma",
  "cmt",
  "cna",
  "cna/gna",
  "cna/resident assistant",
  "companion",
  "crma",
  "dialysis assistant",
  "dialysis tech",
  "direct care assistant",
  "direct care professional",
  "direct care worker",
  "direct health professional",
  "direct support professional",
  "direct support specialist",
  "direct support worker",
  "dsp",
  "emergency room tech",
  "emergency room technician",
  "emergency technician",
  "er tech",
  "geriatric aide",
  "geriatric nurse assistant",
  "geriatric nurse's aide",
  "geriatric nursing assistant",
  "getiatric nurse aide",
  "gna",
  "gna/cna",
  "habilitation tech",
  "health tech",
  "hha",
  "home aide",
  "home care aide",
  "home care provider",
  "home care worker",
  "home health aide",
  "home healthcare aide",
  "home healthcare worker",
  "homemaker",
  "hospice aide",
  "hospice tech",
  "hospice worker",
  "hospitality aide",
  "licensed nursing assistant",
  "lna",
  "lpn",
  "lvn",
  "maa",
  "med assistant",
  "med tech",
  "medical administrative assistant",
  "medical assistant",
  "medicall assistant",
  "medication associate",
  "medication tech",
  "medication technician",
  "medicine tech",
  "multi-skilled tech",
  "multi-skilled technician",
  "nst",
  "nurse",
  "nurse aide",
  "nurse assistant",
  "nurse attendant",
  "nurse support tech",
  "nurse tech",
  "nurse's aide",
  "nursing assistant",
  "nursing tech",
  "nursing technician",
  "nuse support tech",
  "ob tech",
  "obstetrics tech",
  "orderly",
  "palliative care assistant",
  "patient care assistant",
  "patient care tech",
  "patient safety observer",
  "patient transporter",
  "pca",
  "pct",
  "pediatric multi-functional tech",
  "personal care aide",
  "personal care assistant",
  "personal care associate",
  "personal support professional",
  "personal support specialist",
  "personal support staff",
  "personal support worker",
  "phlebotomist",
  "phlebotomy",
  "phlebotomy tech",
  "practical nurse",
  "practical nursing",
  "psw",
  "rca",
  "registered nurse",
  "rehab care tech",
  "resident assistant",
  "resident assistant/cna",
  "resident care advisor",
  "resident care assistant",
  "resident caregiver",
  "resident companion",
  "residential aide",
  "residential care aide",
  "residential care assistant",
  "residential counselor",
  "residential support companion",
  "restorative aide",
  "restorative care aide",
  "rn",
  "rna",
  "safety observation tech",
  "sitter",
  "state-tested nursing assistant",
  "stna",
  "vocational nurse",
  "vocational nursing"
];

function titleIncludesKeyword(title) {
  const lowerCased = title.toLowerCase();
  for (const keyword of KEYWORDS) {
    if (lowerCased.includes(keyword)) {
      return true;
    }
  }
  return false;
}

module.exports = { titleIncludesKeyword };
